x-common-env: &common-env
  env_file:
    - .env
    - .env.dev

services:
  postgres:
    <<: *common-env
    image: timescale/timescaledb-ha:pg16
    restart: unless-stopped
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-p", "${PG_PORT}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    <<: *common-env
    image: redis:7-bookworm
    restart: unless-stopped
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-dev_password}
    ports:
      - "6379:6379"
      - "6380:6380"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  neo4j:
    <<: *common-env
    image: neo4j:2025-enterprise
    restart: unless-stopped
    container_name: neo4j
    environment:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j_logs:/logs
      - neo4j_config:/config
      - neo4j_data:/data
      - neo4j_plugins:/plugins
      - neo4j_import:/import
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7474" ]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  neo4j_logs:
  neo4j_config:
  neo4j_data:
  neo4j_plugins:
  neo4j_import:
